# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20f6fa6445e73098f0c08ce9feaa8ebd60195ff850baa8d132826985da4c40d527f304d90b214bbd9418601cde499dd22f09202761b71989aaed52b8087c31aa

test:
  secret_key_base: f217bc19b8cf9129ebd2ae9a2b4c8830d04c6001641faaf2812753e6b4f805b4536363e593766a5f606f3f58c883d67d4afad7904d15532a0618b0eb75d9da47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
